#!/usr/bin/env bash
# =============================================================================
# setup-android-sdk.sh
#
# Downloads and configures the Android SDK (and optionally the NDK) inside
# tools/android-sdk/ so that Gradle can build the project locally.
#
# Requirements (provided by .replit nix packages):
#   - jdk21_headless  (JAVA_HOME is set by Nix automatically)
#   - curl
#   - unzip
#
# Usage:
#   bash scripts/setup-android-sdk.sh           # SDK only
#   bash scripts/setup-android-sdk.sh --ndk     # SDK + NDK (~2 GB extra)
# =============================================================================
set -euo pipefail

INSTALL_NDK=false
for arg in "$@"; do
  [[ "$arg" == "--ndk" ]] && INSTALL_NDK=true
done

# ── Paths ─────────────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
TOOLS_DIR="$ROOT_DIR/tools"
ANDROID_SDK_DIR="$TOOLS_DIR/android-sdk"

# ── Versions ──────────────────────────────────────────────────────────────────
# Android Command Line Tools (contains sdkmanager/avdmanager)
CMDLINE_TOOLS_URL="https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip"
# SDK packages to install
SDK_PACKAGES=(
  "platforms;android-35"
  "build-tools;35.0.0"
  "build-tools;34.0.0"   # AGP 8.5/8.6 may auto-select 34 — pre-cache it
  "platform-tools"
)
# NDK (only installed when --ndk flag is passed; ~2 GB download)
NDK_PACKAGE="ndk;27.2.12479018"

# ── Helpers ───────────────────────────────────────────────────────────────────
header() { echo; echo "▶ $*"; }
check() { command -v "$1" &>/dev/null || { echo "ERROR: '$1' not found. Is the Nix environment loaded?"; exit 1; }; }

check java
check curl
check unzip

JAVA_VERSION=$(java -version 2>&1 | head -1)
echo "Java: $JAVA_VERSION"

# ── Step 1: Download cmdline-tools ────────────────────────────────────────────
SDKMANAGER="$ANDROID_SDK_DIR/cmdline-tools/latest/bin/sdkmanager"

if [ -f "$SDKMANAGER" ]; then
  header "Android cmdline-tools already present — skipping download"
else
  header "Downloading Android Command Line Tools..."
  mkdir -p "$TOOLS_DIR" "$ANDROID_SDK_DIR"
  TMP_ZIP="$TOOLS_DIR/cmdline-tools.zip"

  curl -L --retry 3 --progress-bar \
    "$CMDLINE_TOOLS_URL" \
    -o "$TMP_ZIP"

  header "Extracting cmdline-tools..."
  TMP_EXTRACT="$TOOLS_DIR/_cmdline_extract"
  rm -rf "$TMP_EXTRACT"
  unzip -q "$TMP_ZIP" -d "$TMP_EXTRACT"

  # The zip contains a single top-level directory named "cmdline-tools".
  # Android SDK expects it at:  $ANDROID_HOME/cmdline-tools/latest/
  mkdir -p "$ANDROID_SDK_DIR/cmdline-tools"
  rm -rf "$ANDROID_SDK_DIR/cmdline-tools/latest"
  mv "$TMP_EXTRACT/cmdline-tools" "$ANDROID_SDK_DIR/cmdline-tools/latest"

  rm -rf "$TMP_EXTRACT" "$TMP_ZIP"
  echo "  ✓ cmdline-tools installed at $ANDROID_SDK_DIR/cmdline-tools/latest/"
fi

# ── Step 2: Set environment variables ─────────────────────────────────────────
export ANDROID_HOME="$ANDROID_SDK_DIR"
export ANDROID_SDK_ROOT="$ANDROID_SDK_DIR"
export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$PATH"

# ── Step 3: Accept licenses ───────────────────────────────────────────────────
header "Accepting Android SDK licenses..."
# sdkmanager --licenses exits non-zero even when all are accepted; use || true
yes 2>/dev/null | sdkmanager --licenses > /dev/null || true
echo "  ✓ Licenses accepted"

# ── Step 4: Install SDK packages ─────────────────────────────────────────────
header "Installing Android SDK packages..."
sdkmanager "${SDK_PACKAGES[@]}"
echo "  ✓ Installed: ${SDK_PACKAGES[*]}"

# ── Step 5: (Optional) Install NDK ───────────────────────────────────────────
if [ "$INSTALL_NDK" = true ]; then
  header "Installing Android NDK (this downloads ~2 GB)..."
  sdkmanager "$NDK_PACKAGE"
  echo "  ✓ NDK installed: $NDK_PACKAGE"
else
  echo
  echo "  ℹ  NDK not installed (not required for this project)."
  echo "     To install: bash scripts/setup-android-sdk.sh --ndk"
fi

# ── Step 6: Write local.properties ────────────────────────────────────────────
header "Writing local.properties..."
cat > "$ROOT_DIR/local.properties" <<EOF
# Auto-generated by scripts/setup-android-sdk.sh
# Do not commit this file — it is machine-specific.
sdk.dir=$ANDROID_SDK_DIR
EOF
echo "  ✓ local.properties → sdk.dir=$ANDROID_SDK_DIR"

# ── Done ──────────────────────────────────────────────────────────────────────
echo
echo "══════════════════════════════════════════════════════"
echo "  ✅  Android SDK setup complete!"
echo ""
echo "  ANDROID_HOME  = $ANDROID_SDK_DIR"
echo "  JAVA_HOME     = ${JAVA_HOME:-"(set by Nix)"}"
echo ""
echo "  Next step: bash scripts/build.sh"
echo "══════════════════════════════════════════════════════"
